# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoRssReader < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/umaidashi/go-rss-reader/releases/download/v0.0.3/go-rss-reader_0.0.3_darwin_amd64.tar.gz"
      sha256 "829a60c4bef1805bbc6cef76ef848b651bf706b49ca68f4b2e93a47eb800c703"

      def install
        bin.install "go-rss-reader"
      end
    end
    on_arm do
      url "https://github.com/umaidashi/go-rss-reader/releases/download/v0.0.3/go-rss-reader_0.0.3_darwin_arm64.tar.gz"
      sha256 "88f1cc32be40ab05d529c001f204d0be684b676b5dee358a0175fe4ff0c7a976"

      def install
        bin.install "go-rss-reader"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/umaidashi/go-rss-reader/releases/download/v0.0.3/go-rss-reader_0.0.3_linux_amd64.tar.gz"
        sha256 "e4c59124fa6784e85cb0bd0986b7e0d076e69303bef3689499f091bd97bcf1fc"

        def install
          bin.install "go-rss-reader"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/umaidashi/go-rss-reader/releases/download/v0.0.3/go-rss-reader_0.0.3_linux_arm64.tar.gz"
        sha256 "3667d1013155d14f552376c25b2721256d085ef16bdb1c52ebe65cd0cd9526e9"

        def install
          bin.install "go-rss-reader"
        end
      end
    end
  end
end
