# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grr < Formula
  desc ""
  homepage ""
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/umaidashi/grr/releases/download/v0.0.4/grr_0.0.4_darwin_amd64.tar.gz"
      sha256 "8b6c895cb6e1b84dee22db15348836a3e8fecd9afbb8809c3047c4aec30c039b"

      def install
        bin.install "grr"
      end
    end
    on_arm do
      url "https://github.com/umaidashi/grr/releases/download/v0.0.4/grr_0.0.4_darwin_arm64.tar.gz"
      sha256 "bbe1e8b11a6cd04b71878e1c307ee30a2f47973dec8125236211ca4edb8797b0"

      def install
        bin.install "grr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/umaidashi/grr/releases/download/v0.0.4/grr_0.0.4_linux_amd64.tar.gz"
        sha256 "5fb92ee2c95040143b29f1f72ba0853144d54b8ea3fb566f2bf87a54a46dc60c"

        def install
          bin.install "grr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/umaidashi/grr/releases/download/v0.0.4/grr_0.0.4_linux_arm64.tar.gz"
        sha256 "576b140e3d4a5d9f097e182f8bb2cba75770a8f67325c82aba8e3ffe8cf74f58"

        def install
          bin.install "grr"
        end
      end
    end
  end
end
